function [] = analysis2latex(Analysis,dir_ref)

filename = 'LaTeXTables.txt';
filepath = [dir_ref,'/',filename];
datasource = dir_ref(24:end-3);

lines = 91;
tobuild = cell(lines,1);

%Begin Activity Potential Results
tobuild{01} = ['%Data From: ',datasource];
tobuild{02} = ['\subsection{Results: ',datasource,' [',num2str(Analysis.NumberPeople),' Students]}'];
tobuild{03} = '\begin{tabular}{|c|c|c||c|c||c|c||c|c||c|c|} \hline';
tobuild{04} = '\multicolumn{3}{|c||}{Activity Pot.} & \multicolumn{2}{c||}{\textbf{Exponential}} & \multicolumn{2}{c||}{\textbf{Gamma}} & \multicolumn{2}{c||}{\textbf{Rayleigh}} & \multicolumn{2}{c|}{\textbf{Log-Normal}} \\ \hline';
tobuild{05} = ['\parbox[t]{2mm}{\multirow{12}{*}{\rotatebox[origin=c]{90}{Method of Moments}}} & \multicolumn{2}{|c||}{\multirow{2}{*}{\textbf{Parameters}}} & \multirow{2}{*}{Rate} & \multirow{2}{*}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Exponential.Parameters.Scale),'$} & Shape & $',num2matlabstr(Analysis.ActivityPotential_Moments.Gamma.Parameters.Shape),'$ & \multirow{2}{*}{Scale} & \multirow{2}{*}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Rayleigh.Parameters.Scale),'$} & Loc. & $',num2matlabstr(Analysis.ActivityPotential_Moments.LogNormal.Parameters.Location),'$ \\ \cline{6-7}\cline{10-11}'];
tobuild{06} = ['& \multicolumn{2}{|c||}{} & & & Scale & $',num2matlabstr(Analysis.ActivityPotential_Moments.Gamma.Parameters.Scale),'$ & & & Scale & $',num2matlabstr(Analysis.ActivityPotential_Moments.LogNormal.Parameters.Scale),'$ \\ \cline{2-11}'];
tobuild{07} = ['& \parbox[t]{2mm}{\multirow{5}{*}{\rotatebox[origin=c]{90}{Statistics}}} & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Exponential.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Gamma.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Rayleigh.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_Moments.LogNormal.Statistics.Kolmogorov_D),'$} \\ \cline{3-11}'];
tobuild{08} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Exponential.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Gamma.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Rayleigh.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_Moments.LogNormal.Statistics.Cramer_von_Mises),'$} \\ \cline{3-11}'];
tobuild{09} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Exponential.Statistics.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Gamma.Statistics.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Rayleigh.Statistics.Kuiper),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_Moments.LogNormal.Statistics.Kuiper),'$} \\ \cline{3-11}'];
tobuild{10} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Exponential.Statistics.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Gamma.Statistics.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Rayleigh.Statistics.Watson),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_Moments.LogNormal.Statistics.Watson),'$} \\ \cline{3-11}'];
tobuild{11} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Exponential.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Gamma.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Rayleigh.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_Moments.LogNormal.Statistics.Anderson_Darling),'$} \\ \cline{2-11}'];
tobuild{12} = ['& \parbox[t]{2mm}{\multirow{5}{*}{\rotatebox[origin=c]{90}{p-Values}}} & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Exponential.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Gamma.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Rayleigh.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_Moments.LogNormal.pValues.Kolmogorov_D),'$} \\ \cline{3-11}'];
tobuild{13} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Exponential.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Gamma.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Rayleigh.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_Moments.LogNormal.pValues.Cramer_von_Mises),'$} \\ \cline{3-11}'];
tobuild{14} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Exponential.pValues.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Gamma.pValues.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Rayleigh.pValues.Kuiper),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_Moments.LogNormal.pValues.Kuiper),'$} \\ \cline{3-11}'];
tobuild{15} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Exponential.pValues.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Gamma.pValues.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Rayleigh.pValues.Watson),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_Moments.LogNormal.pValues.Watson),'$} \\ \cline{3-11}'];
tobuild{16} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Exponential.pValues.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Gamma.pValues.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Rayleigh.pValues.Anderson_Darling),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_Moments.LogNormal.pValues.Anderson_Darling),'$} \\ \hline \hline'];
tobuild{17} = ['\parbox[t]{2mm}{\multirow{12}{*}{\rotatebox[origin=c]{90}{Curve Fitting Tool}}} & \multicolumn{2}{|c||}{\multirow{2}{*}{\textbf{Parameters}}} & \multirow{2}{*}{Rate} & \multirow{2}{*}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Exponential.Parameters.Scale),'$} & Shape & $',num2matlabstr(Analysis.ActivityPotential_FitTool.Gamma.Parameters.Shape),'$ & \multirow{2}{*}{Scale} & \multirow{2}{*}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Rayleigh.Parameters.Scale),'$} & Loc. & $',num2matlabstr(Analysis.ActivityPotential_FitTool.LogNormal.Parameters.Location),'$ \\ \cline{6-7}\cline{10-11}'];
tobuild{18} = ['& \multicolumn{2}{|c||}{} & & & Scale & $',num2matlabstr(Analysis.ActivityPotential_FitTool.Gamma.Parameters.Scale),'$ & & & Scale & $',num2matlabstr(Analysis.ActivityPotential_FitTool.LogNormal.Parameters.Scale),'$ \\ \cline{2-11}'];
tobuild{19} = ['& \parbox[t]{2mm}{\multirow{5}{*}{\rotatebox[origin=c]{90}{Statistics}}} & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Exponential.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Gamma.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Rayleigh.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.LogNormal.Statistics.Kolmogorov_D),'$} \\ \cline{3-11}'];
tobuild{20} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Exponential.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Gamma.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Rayleigh.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.LogNormal.Statistics.Cramer_von_Mises),'$} \\ \cline{3-11}'];
tobuild{21} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Exponential.Statistics.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Gamma.Statistics.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Rayleigh.Statistics.Kuiper),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.LogNormal.Statistics.Kuiper),'$} \\ \cline{3-11}'];
tobuild{22} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Exponential.Statistics.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Gamma.Statistics.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Rayleigh.Statistics.Watson),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.LogNormal.Statistics.Watson),'$} \\ \cline{3-11}'];
tobuild{23} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Exponential.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Gamma.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Rayleigh.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.LogNormal.Statistics.Anderson_Darling),'$} \\ \cline{2-11}'];
tobuild{24} = ['& \parbox[t]{2mm}{\multirow{5}{*}{\rotatebox[origin=c]{90}{p-Values}}} & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Exponential.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Gamma.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Rayleigh.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.LogNormal.pValues.Kolmogorov_D),'$} \\ \cline{3-11}'];
tobuild{25} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Exponential.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Gamma.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Rayleigh.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.LogNormal.pValues.Cramer_von_Mises),'$} \\ \cline{3-11}'];
tobuild{26} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Exponential.pValues.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Gamma.pValues.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Rayleigh.pValues.Kuiper),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.LogNormal.pValues.Kuiper),'$} \\ \cline{3-11}'];
tobuild{27} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Exponential.pValues.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Gamma.pValues.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Rayleigh.pValues.Watson),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.LogNormal.pValues.Watson),'$} \\ \cline{3-11}'];
tobuild{28} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Exponential.pValues.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Gamma.pValues.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Rayleigh.pValues.Anderson_Darling),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.LogNormal.pValues.Anderson_Darling),'$} \\ \hline'];
tobuild{29} = '\end{tabular}';
%Begin Interaction Times Results
tobuild{30} = '\newpage';
tobuild{31} = '\begin{tabular}{|c|c|c||c|c||c|c||c|c||c|c|} \hline';
tobuild{32} = '\multicolumn{3}{|c||}{Int. Times} & \multicolumn{2}{c||}{\textbf{Exponential}} & \multicolumn{2}{c||}{\textbf{Mittag-Leffler}} & \multicolumn{2}{c||}{\textbf{Gen. Pareto}} & \multicolumn{2}{c|}{\textbf{Weibull}} \\ \hline';
tobuild{33} = ['\parbox[t]{2mm}{\multirow{7}{*}{\rotatebox[origin=c]{90}{Method of Moments}}} & \multicolumn{2}{|c||}{\multirow{3}{*}{\textbf{Parameters}}} & \multirow{3}{*}{Rate} & \multirow{3}{*}{$',num2matlabstr(Analysis.InteractionTimes_Moments.Exponential.Parameters.Scale),'$} & Stability & $X$ & Shape & $',num2matlabstr(Analysis.InteractionTimes_Moments.GenPareto.Parameters.Shape),'$ & Scale & $X$ \\ \cline{6-11}'];
tobuild{34} = ['& \multicolumn{2}{|c||}{} & & & \multirow{2}{*}{Scale} & \multirow{2}{*}{$X$} & Scale & $',num2matlabstr(Analysis.InteractionTimes_Moments.GenPareto.Parameters.Scale),'$ & \multirow{2}{*}{Shape} & \multirow{2}{*}{$X$} \\ \cline{8-9}'];
tobuild{35} = ['& \multicolumn{2}{|c||}{} & & & & & Loc. & $',num2matlabstr(Analysis.InteractionTimes_Moments.GenPareto.Parameters.Location),'$ & & \\ \cline{2-11}'];
tobuild{36} = ['& \parbox[t]{2mm}{\multirow{2}{*}{\rotatebox[origin=c]{90}{Statistics}}} & Mod Kol & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.Exponential.Statistics.Modified_Kol),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.GenPareto.Statistics.Modified_Kol),'$} & \multicolumn{2}{c|}{$X$} \\ \cline{3-11}'];
tobuild{37} = ['& & $\chi^{2}$ & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.Exponential.Statistics.Chi_Squared),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.GenPareto.Statistics.Chi_Squared),'$} & \multicolumn{2}{c|}{$X$} \\ \cline{2-11}'];
tobuild{38} = ['& \parbox[t]{2mm}{\multirow{2}{*}{\rotatebox[origin=c]{90}{p-Values}}} & Mod Kol & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.Exponential.pValues.Modified_Kol),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.GenPareto.pValues.Modified_Kol),'$} & \multicolumn{2}{c|}{$X$} \\ \cline{3-11}'];
tobuild{39} = ['& & $\chi^{2}$ & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.Exponential.pValues.Chi_Squared),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.GenPareto.pValues.Chi_Squared),'$} & \multicolumn{2}{c|}{$X$} \\ \hline \hline'];
tobuild{40} = ['\parbox[t]{2mm}{\multirow{7}{*}{\rotatebox[origin=c]{90}{Curve Fitting Tool}}} & \multicolumn{2}{|c||}{\multirow{3}{*}{\textbf{Parameters}}} & \multirow{3}{*}{Rate} & \multirow{3}{*}{$',num2matlabstr(Analysis.InteractionTimes_FitTool.Exponential.Parameters.Scale),'$} & Stability & $',num2matlabstr(Analysis.InteractionTimes_FitTool.MittagLeffler.Parameters.Stability),'$ & Shape & $',num2matlabstr(Analysis.InteractionTimes_FitTool.GenPareto.Parameters.Shape),'$ & Scale & $',num2matlabstr(Analysis.InteractionTimes_FitTool.Weibull.Parameters.Scale),'$ \\ \cline{6-11}'];
tobuild{41} = ['& \multicolumn{2}{|c||}{} & & & \multirow{2}{*}{Scale} & \multirow{2}{*}{$',num2matlabstr(Analysis.InteractionTimes_FitTool.MittagLeffler.Parameters.Scale),'$} & Scale & $',num2matlabstr(Analysis.InteractionTimes_FitTool.GenPareto.Parameters.Scale),'$ & \multirow{2}{*}{Shape} & \multirow{2}{*}{$',num2matlabstr(Analysis.InteractionTimes_FitTool.Weibull.Parameters.Shape),'$} \\ \cline{8-9}'];
tobuild{42} = ['& \multicolumn{2}{|c||}{} & & & & & Loc. & $',num2matlabstr(Analysis.InteractionTimes_FitTool.GenPareto.Parameters.Location),'$ & & \\ \cline{2-11}'];
tobuild{43} = ['& \parbox[t]{2mm}{\multirow{2}{*}{\rotatebox[origin=c]{90}{Statistics}}} & Mod Kol & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_FitTool.Exponential.Statistics.Modified_Kol),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_FitTool.MittagLeffler.Statistics.Modified_Kol),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_FitTool.GenPareto.Statistics.Modified_Kol),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.InteractionTimes_FitTool.Weibull.Statistics.Modified_Kol),'$} \\ \cline{3-11}'];
tobuild{44} = ['& & $\chi^{2}$ & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_FitTool.Exponential.Statistics.Chi_Squared),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_FitTool.MittagLeffler.Statistics.Chi_Squared),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_FitTool.GenPareto.Statistics.Chi_Squared),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.InteractionTimes_FitTool.Weibull.Statistics.Chi_Squared),'$} \\ \cline{1-11}'];
tobuild{45} = ['& \parbox[t]{2mm}{\multirow{2}{*}{\rotatebox[origin=c]{90}{p-Values}}} & Mod Kol & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_FitTool.Exponential.pValues.Modified_Kol),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_FitTool.MittagLeffler.pValues.Modified_Kol),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_FitTool.GenPareto.pValues.Modified_Kol),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.InteractionTimes_FitTool.Weibull.pValues.Modified_Kol),'$} \\ \cline{3-11}'];
tobuild{46} = ['& & $\chi^{2}$ & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_FitTool.Exponential.pValues.Chi_Squared),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_FitTool.MittagLeffler.pValues.Chi_Squared),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_FitTool.GenPareto.pValues.Chi_Squared),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.InteractionTimes_FitTool.Weibull.pValues.Chi_Squared),'$} \\ \hline'];
tobuild{47} = '\end{tabular}';
%Begin Active Links Results
tobuild{48} = '\newpage';
tobuild{49} = '\begin{tabular}{|c|c|c||c|c||c|c||c|c||c|c|} \hline';
tobuild{50} = '\multicolumn{3}{|c||}{Links Active} & \multicolumn{2}{c||}{\textbf{Exponential}} & \multicolumn{2}{c||}{\textbf{Gamma}} & \multicolumn{2}{c||}{\textbf{Rayleigh}} & \multicolumn{2}{c|}{\textbf{Log-Normal}} \\ \hline';
tobuild{51} = ['\parbox[t]{2mm}{\multirow{12}{*}{\rotatebox[origin=c]{90}{Method of Moments}}} & \multicolumn{2}{|c||}{\multirow{2}{*}{\textbf{Parameters}}} & \multirow{2}{*}{Rate} & \multirow{2}{*}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Exponential.Parameters.Scale),'$} & Shape & $',num2matlabstr(Analysis.ActiveLinks_Moments.Gamma.Parameters.Shape),'$ & \multirow{2}{*}{Scale} & \multirow{2}{*}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Rayleigh.Parameters.Scale),'$} & Loc. & $',num2matlabstr(Analysis.ActiveLinks_Moments.LogNormal.Parameters.Location),'$ \\ \cline{6-7}\cline{10-11}'];
tobuild{52} = ['& \multicolumn{2}{|c||}{} & & & Scale & $',num2matlabstr(Analysis.ActiveLinks_Moments.Gamma.Parameters.Scale),'$ & & & Scale & $',num2matlabstr(Analysis.ActiveLinks_Moments.LogNormal.Parameters.Scale),'$ \\ \cline{2-11}'];
tobuild{53} = ['& \parbox[t]{2mm}{\multirow{5}{*}{\rotatebox[origin=c]{90}{Statistics}}} & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Exponential.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Gamma.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Rayleigh.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_Moments.LogNormal.Statistics.Kolmogorov_D),'$} \\ \cline{3-11}'];
tobuild{54} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Exponential.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Gamma.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Rayleigh.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_Moments.LogNormal.Statistics.Cramer_von_Mises),'$} \\ \cline{3-11}'];
tobuild{55} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Exponential.Statistics.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Gamma.Statistics.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Rayleigh.Statistics.Kuiper),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_Moments.LogNormal.Statistics.Kuiper),'$} \\ \cline{3-11}'];
tobuild{56} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Exponential.Statistics.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Gamma.Statistics.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Rayleigh.Statistics.Watson),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_Moments.LogNormal.Statistics.Watson),'$} \\ \cline{3-11}'];
tobuild{57} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Exponential.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Gamma.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Rayleigh.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_Moments.LogNormal.Statistics.Anderson_Darling),'$} \\ \cline{2-11}'];
tobuild{58} = ['& \parbox[t]{2mm}{\multirow{5}{*}{\rotatebox[origin=c]{90}{p-Values}}} & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Exponential.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Gamma.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Rayleigh.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_Moments.LogNormal.pValues.Kolmogorov_D),'$} \\ \cline{3-11}'];
tobuild{59} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Exponential.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Gamma.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Rayleigh.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_Moments.LogNormal.pValues.Cramer_von_Mises),'$} \\ \cline{3-11}'];
tobuild{60} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Exponential.pValues.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Gamma.pValues.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Rayleigh.pValues.Kuiper),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_Moments.LogNormal.pValues.Kuiper),'$} \\ \cline{3-11}'];
tobuild{61} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Exponential.pValues.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Gamma.pValues.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Rayleigh.pValues.Watson),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_Moments.LogNormal.pValues.Watson),'$} \\ \cline{3-11}'];
tobuild{62} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Exponential.pValues.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Gamma.pValues.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Rayleigh.pValues.Anderson_Darling),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_Moments.LogNormal.pValues.Anderson_Darling),'$} \\ \hline \hline'];
tobuild{63} = ['\parbox[t]{2mm}{\multirow{12}{*}{\rotatebox[origin=c]{90}{Curve Fitting Tool}}} & \multicolumn{2}{|c||}{\multirow{2}{*}{\textbf{Parameters}}} & \multirow{2}{*}{Rate} & \multirow{2}{*}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Exponential.Parameters.Scale),'$} & Shape & $',num2matlabstr(Analysis.ActiveLinks_FitTool.Gamma.Parameters.Shape),'$ & \multirow{2}{*}{Scale} & \multirow{2}{*}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Rayleigh.Parameters.Scale),'$} & Loc. & $',num2matlabstr(Analysis.ActiveLinks_FitTool.LogNormal.Parameters.Location),'$ \\ \cline{6-7}\cline{10-11}'];
tobuild{64} = ['& \multicolumn{2}{|c||}{} & & & Scale & $',num2matlabstr(Analysis.ActiveLinks_FitTool.Gamma.Parameters.Scale),'$ & & & Scale & $',num2matlabstr(Analysis.ActiveLinks_FitTool.LogNormal.Parameters.Scale),'$ \\ \cline{2-11}'];
tobuild{65} = ['& \parbox[t]{2mm}{\multirow{5}{*}{\rotatebox[origin=c]{90}{Statistics}}} & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Exponential.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Gamma.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Rayleigh.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.LogNormal.Statistics.Kolmogorov_D),'$} \\ \cline{3-11}'];
tobuild{66} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Exponential.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Gamma.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Rayleigh.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.LogNormal.Statistics.Cramer_von_Mises),'$} \\ \cline{3-11}'];
tobuild{67} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Exponential.Statistics.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Gamma.Statistics.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Rayleigh.Statistics.Kuiper),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.LogNormal.Statistics.Kuiper),'$} \\ \cline{3-11}'];
tobuild{68} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Exponential.Statistics.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Gamma.Statistics.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Rayleigh.Statistics.Watson),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.LogNormal.Statistics.Watson),'$} \\ \cline{3-11}'];
tobuild{69} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Exponential.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Gamma.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Rayleigh.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.LogNormal.Statistics.Anderson_Darling),'$} \\ \cline{2-11}'];
tobuild{70} = ['& \parbox[t]{2mm}{\multirow{5}{*}{\rotatebox[origin=c]{90}{p-Values}}} & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Exponential.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Gamma.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Rayleigh.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.LogNormal.pValues.Kolmogorov_D),'$} \\ \cline{3-11}'];
tobuild{71} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Exponential.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Gamma.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Rayleigh.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.LogNormal.pValues.Cramer_von_Mises),'$} \\ \cline{3-11}'];
tobuild{72} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Exponential.pValues.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Gamma.pValues.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Rayleigh.pValues.Kuiper),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.LogNormal.pValues.Kuiper),'$} \\ \cline{3-11}'];
tobuild{73} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Exponential.pValues.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Gamma.pValues.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Rayleigh.pValues.Watson),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.LogNormal.pValues.Watson),'$} \\ \cline{3-11}'];
tobuild{74} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Exponential.pValues.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Gamma.pValues.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Rayleigh.pValues.Anderson_Darling),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.LogNormal.pValues.Anderson_Darling),'$} \\ \hline'];
tobuild{75} = '\end{tabular}';
%Begin No Contact Time Results
tobuild{76} = '\newpage';
tobuild{77} = '\begin{tabular}{|c|c|c||c|c||c|c||c|c||c|c|} \hline';
tobuild{78} = '\multicolumn{3}{|c||}{Time Between Events} & \multicolumn{2}{c||}{\textbf{Exponential}} & \multicolumn{2}{c||}{\textbf{Gamma}} & \multicolumn{2}{c||}{\textbf{Rayleigh}} & \multicolumn{2}{c|}{\textbf{Log-Normal}} \\ \hline';
tobuild{79} = ['\parbox[t]{2mm}{\multirow{6}{*}{\rotatebox[origin=c]{90}{Method of Moments}}} & \multicolumn{2}{|c||}{\multirow{2}{*}{\textbf{Parameters}}} & \multirow{2}{*}{Rate} & \multirow{2}{*}{$',num2matlabstr(Analysis.NoContactTimes_Moments.Exponential.Parameters.Scale),'$} & Shape & $',num2matlabstr(Analysis.NoContactTimes_Moments.Gamma.Parameters.Shape),'$ & \multirow{2}{*}{Scale} & \multirow{2}{*}{$',num2matlabstr(Analysis.NoContactTimes_Moments.Rayleigh.Parameters.Scale),'$} & Loc. & $',num2matlabstr(Analysis.NoContactTimes_Moments.LogNormal.Parameters.Location),'$ \\ \cline{6-7}\cline{10-11}'];
tobuild{80} = ['& \multicolumn{2}{|c||}{} & & & Scale & $',num2matlabstr(Analysis.NoContactTimes_Moments.Gamma.Parameters.Scale),'$ & & & Scale & $',num2matlabstr(Analysis.NoContactTimes_Moments.LogNormal.Parameters.Scale),'$ \\ \cline{2-11}'];
tobuild{81} = ['& \parbox[t]{2mm}{\multirow{2}{*}{\rotatebox[origin=c]{90}{Statistics}}} & Mod Kol & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.NoContactTimes_Moments.Exponential.Statistics.Modified_Kol),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.NoContactTimes_Moments.Gamma.Statistics.Modified_Kol),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.NoContactTimes_Moments.Rayleigh.Statistics.Modified_Kol),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.NoContactTimes_Moments.LogNormal.Statistics.Modified_Kol),'$} \\ \cline{3-11}'];
tobuild{82} = ['& & $\chi^{2}$ & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.NoContactTimes_Moments.Exponential.Statistics.Chi_Squared),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.NoContactTimes_Moments.Gamma.Statistics.Chi_Squared),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.NoContactTimes_Moments.Rayleigh.Statistics.Chi_Squared),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.NoContactTimes_Moments.LogNormal.Statistics.Chi_Squared),'$} \\ \cline{2-11}'];
tobuild{83} = ['& \parbox[t]{2mm}{\multirow{2}{*}{\rotatebox[origin=c]{90}{p-Values}}} & Mod Kol & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.NoContactTimes_Moments.Exponential.pValues.Modified_Kol),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.NoContactTimes_Moments.Gamma.pValues.Modified_Kol),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.NoContactTimes_Moments.Rayleigh.pValues.Modified_Kol),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.NoContactTimes_Moments.LogNormal.pValues.Modified_Kol),'$} \\ \cline{3-11}'];
tobuild{84} = ['& & $\chi^{2}$ & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.NoContactTimes_Moments.Exponential.pValues.Chi_Squared),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.NoContactTimes_Moments.Gamma.pValues.Chi_Squared),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.NoContactTimes_Moments.Rayleigh.pValues.Chi_Squared),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.NoContactTimes_Moments.LogNormal.pValues.Chi_Squared),'$} \\ \hline \hline'];
tobuild{85} = ['\parbox[t]{2mm}{\multirow{6}{*}{\rotatebox[origin=c]{90}{Curve Fitting Tool}}} & \multicolumn{2}{|c||}{\multirow{2}{*}{\textbf{Parameters}}} & \multirow{2}{*}{Rate} & \multirow{2}{*}{$',num2matlabstr(Analysis.NoContactTimes_FitTool.Exponential.Parameters.Scale),'$} & Shape & $',num2matlabstr(Analysis.NoContactTimes_FitTool.Gamma.Parameters.Shape),'$ & \multirow{2}{*}{Scale} & \multirow{2}{*}{$',num2matlabstr(Analysis.NoContactTimes_FitTool.Rayleigh.Parameters.Scale),'$} & Loc. & $',num2matlabstr(Analysis.NoContactTimes_FitTool.LogNormal.Parameters.Location),'$ \\ \cline{6-7}\cline{10-11}'];
tobuild{86} = ['& \multicolumn{2}{|c||}{} & & & Scale & $',num2matlabstr(Analysis.NoContactTimes_FitTool.Gamma.Parameters.Scale),'$ & & & Scale & $',num2matlabstr(Analysis.NoContactTimes_FitTool.LogNormal.Parameters.Scale),'$ \\ \cline{2-11}'];
tobuild{87} = ['& \parbox[t]{2mm}{\multirow{2}{*}{\rotatebox[origin=c]{90}{Statistics}}} & Mod Kol & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.NoContactTimes_FitTool.Exponential.Statistics.Modified_Kol),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.NoContactTimes_FitTool.Gamma.Statistics.Modified_Kol),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.NoContactTimes_FitTool.Rayleigh.Statistics.Modified_Kol),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.NoContactTimes_FitTool.LogNormal.Statistics.Modified_Kol),'$} \\ \cline{3-11}'];
tobuild{88} = ['& & $\chi^{2}$ & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.NoContactTimes_FitTool.Exponential.Statistics.Chi_Squared),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.NoContactTimes_FitTool.Gamma.Statistics.Chi_Squared),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.NoContactTimes_FitTool.Rayleigh.Statistics.Chi_Squared),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.NoContactTimes_FitTool.LogNormal.Statistics.Chi_Squared),'$} \\ \cline{2-11}'];
tobuild{89} = ['& \parbox[t]{2mm}{\multirow{2}{*}{\rotatebox[origin=c]{90}{p-Values}}} & Mod Kol & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.NoContactTimes_FitTool.Exponential.pValues.Modified_Kol),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.NoContactTimes_FitTool.Gamma.pValues.Modified_Kol),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.NoContactTimes_FitTool.Rayleigh.pValues.Modified_Kol),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.NoContactTimes_FitTool.LogNormal.pValues.Modified_Kol),'$} \\ \cline{3-11}'];
tobuild{90} = ['& & $\chi^{2}$ & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.NoContactTimes_FitTool.Exponential.pValues.Chi_Squared),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.NoContactTimes_FitTool.Gamma.pValues.Chi_Squared),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.NoContactTimes_FitTool.Rayleigh.pValues.Chi_Squared),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.NoContactTimes_FitTool.LogNormal.pValues.Chi_Squared),'$} \\ \hline'];
tobuild{91} = '\end{tabular}';

fileID = fopen(filepath,'w');
fprintf(fileID,'%s\r\n',tobuild{:});
fclose(fileID);

end

