function [] = analysis2latex(Analysis,dir_ref)

filename = 'LaTeXTables.txt';
filepath = [dir_ref,'/',filename];

lines = 111;
tobuild = cell(lines,1);

%Begin Activity Potential Results
tobuild{001} = '\newpage';
tobuild{002} = '\section{Results: Data Source}';
tobuild{003} = '\begin{tabular}{|c|c|c||c|c||c|c||c|c||c|c|} \hline';
tobuild{004} = '\multicolumn{3}{|c||}{Activity Pot.} & \multicolumn{2}{c||}{\textbf{Exponential}} & \multicolumn{2}{c||}{\textbf{Gamma}} & \multicolumn{2}{c||}{\textbf{Rayleigh}} & \multicolumn{2}{c|}{\textbf{Log-Normal}} \\ \hline';
tobuild{005} = ['\parbox[t]{2mm}{\multirow{16}{*}{\rotatebox[origin=c]{90}{Method of Moments}}} & \multicolumn{2}{|c||}{\multirow{2}{*}{\textbf{Parameters}}} & \multirow{2}{*}{Rate} & \multirow{2}{*}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Exponential.Parameters.Scale),'$} & Shape & $',num2matlabstr(Analysis.ActivityPotential_Moments.Gamma.Parameters.Shape),'$ & \multirow{2}{*}{Scale} & \multirow{2}{*}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Rayleigh.Parameters.Scale),'$} & Loc. & $',num2matlabstr(Analysis.ActivityPotential_Moments.LogNormal.Parameters.Location),'$ \\ \cline{6-7}\cline{10-11}'];
tobuild{006} = ['& \multicolumn{2}{|c||}{} & & & Scale & $',num2matlabstr(Analysis.ActivityPotential_Moments.Gamma.Parameters.Scale),'$ & & & Scale & $',num2matlabstr(Analysis.ActivityPotential_Moments.LogNormal.Parameters.Scale),'$ \\ \cline{2-11}'];
tobuild{007} = ['& \parbox[t]{2mm}{\multirow{7}{*}{\rotatebox[origin=c]{90}{Statistics}}} & Kol D+ & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Exponential.Statistics.Kolmogorov_D_Plus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Gamma.Statistics.Kolmogorov_D_Plus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Rayleigh.Statistics.Kolmogorov_D_Plus),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_Moments.LogNormal.Statistics.Kolmogorov_D_Plus),'$} \\ \cline{3-11}'];
tobuild{008} = ['& & Kol D- & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Exponential.Statistics.Kolmogorov_D_Minus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Gamma.Statistics.Kolmogorov_D_Minus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Rayleigh.Statistics.Kolmogorov_D_Minus),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_Moments.LogNormal.Statistics.Kolmogorov_D_Minus),'$} \\ \cline{3-11}'];
tobuild{009} = ['& & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Exponential.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Gamma.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Rayleigh.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_Moments.LogNormal.Statistics.Kolmogorov_D),'$} \\ \cline{3-11}'];
tobuild{010} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Exponential.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Gamma.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Rayleigh.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_Moments.LogNormal.Statistics.Cramer_von_Mises),'$} \\ \cline{3-11}'];
tobuild{011} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Exponential.Statistics.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Gamma.Statistics.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Rayleigh.Statistics.Kuiper),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_Moments.LogNormal.Statistics.Kuiper),'$} \\ \cline{3-11}'];
tobuild{012} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Exponential.Statistics.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Gamma.Statistics.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Rayleigh.Statistics.Watson),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_Moments.LogNormal.Statistics.Watson),'$} \\ \cline{3-11}'];
tobuild{013} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Exponential.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Gamma.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Rayleigh.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_Moments.LogNormal.Statistics.Anderson_Darling),'$} \\ \cline{2-11}'];
tobuild{014} = ['& \parbox[t]{2mm}{\multirow{7}{*}{\rotatebox[origin=c]{90}{p-Values}}} & Kol D+ & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Exponential.pValues.Kolmogorov_D_Plus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Gamma.pValues.Kolmogorov_D_Plus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Rayleigh.pValues.Kolmogorov_D_Plus),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_Moments.LogNormal.pValues.Kolmogorov_D_Plus),'$} \\ \cline{3-11}'];
tobuild{015} = ['& & Kol D- & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Exponential.pValues.Kolmogorov_D_Minus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Gamma.pValues.Kolmogorov_D_Minus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Rayleigh.pValues.Kolmogorov_D_Minus),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_Moments.LogNormal.pValues.Kolmogorov_D_Minus),'$} \\ \cline{3-11}'];
tobuild{016} = ['& & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Exponential.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Gamma.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Rayleigh.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_Moments.LogNormal.pValues.Kolmogorov_D),'$} \\ \cline{3-11}'];
tobuild{017} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Exponential.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Gamma.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Rayleigh.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_Moments.LogNormal.pValues.Cramer_von_Mises),'$} \\ \cline{3-11}'];
tobuild{018} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Exponential.pValues.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Gamma.pValues.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Rayleigh.pValues.Kuiper),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_Moments.LogNormal.pValues.Kuiper),'$} \\ \cline{3-11}'];
tobuild{019} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Exponential.pValues.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Gamma.pValues.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Rayleigh.pValues.Watson),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_Moments.LogNormal.pValues.Watson),'$} \\ \cline{3-11}'];
tobuild{020} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Exponential.pValues.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Gamma.pValues.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_Moments.Rayleigh.pValues.Anderson_Darling),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_Moments.LogNormal.pValues.Anderson_Darling),'$} \\ \hline \hline'];
tobuild{021} = ['\parbox[t]{2mm}{\multirow{16}{*}{\rotatebox[origin=c]{90}{Curve Fitting Tool}}} & \multicolumn{2}{|c||}{\multirow{2}{*}{\textbf{Parameters}}} & \multirow{2}{*}{Rate} & \multirow{2}{*}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Exponential.Parameters.Scale),'$} & Shape & $',num2matlabstr(Analysis.ActivityPotential_FitTool.Gamma.Parameters.Shape),'$ & \multirow{2}{*}{Scale} & \multirow{2}{*}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Rayleigh.Parameters.Scale),'$} & Loc. & $',num2matlabstr(Analysis.ActivityPotential_FitTool.LogNormal.Parameters.Location),'$ \\ \cline{6-7}\cline{10-11}'];
tobuild{022} = ['& \multicolumn{2}{|c||}{} & & & Scale & $',num2matlabstr(Analysis.ActivityPotential_FitTool.Gamma.Parameters.Scale),'$ & & & Scale & $',num2matlabstr(Analysis.ActivityPotential_FitTool.LogNormal.Parameters.Scale),'$ \\ \cline{2-11}'];
tobuild{023} = ['& \parbox[t]{2mm}{\multirow{7}{*}{\rotatebox[origin=c]{90}{Statistics}}} & Kol D+ & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Exponential.Statistics.Kolmogorov_D_Plus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Gamma.Statistics.Kolmogorov_D_Plus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Rayleigh.Statistics.Kolmogorov_D_Plus),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.LogNormal.Statistics.Kolmogorov_D_Plus),'$} \\ \cline{3-11}'];
tobuild{024} = ['& & Kol D- & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Exponential.Statistics.Kolmogorov_D_Minus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Gamma.Statistics.Kolmogorov_D_Minus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Rayleigh.Statistics.Kolmogorov_D_Minus),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.LogNormal.Statistics.Kolmogorov_D_Minus),'$} \\ \cline{3-11}'];
tobuild{025} = ['& & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Exponential.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Gamma.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Rayleigh.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.LogNormal.Statistics.Kolmogorov_D),'$} \\ \cline{3-11}'];
tobuild{026} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Exponential.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Gamma.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Rayleigh.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.LogNormal.Statistics.Cramer_von_Mises),'$} \\ \cline{3-11}'];
tobuild{027} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Exponential.Statistics.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Gamma.Statistics.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Rayleigh.Statistics.Kuiper),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.LogNormal.Statistics.Kuiper),'$} \\ \cline{3-11}'];
tobuild{028} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Exponential.Statistics.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Gamma.Statistics.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Rayleigh.Statistics.Watson),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.LogNormal.Statistics.Watson),'$} \\ \cline{3-11}'];
tobuild{029} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Exponential.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Gamma.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Rayleigh.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.LogNormal.Statistics.Anderson_Darling),'$} \\ \cline{2-11}'];
tobuild{030} = ['& \parbox[t]{2mm}{\multirow{7}{*}{\rotatebox[origin=c]{90}{p-Values}}} & Kol D+ & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Exponential.pValues.Kolmogorov_D_Plus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Gamma.pValues.Kolmogorov_D_Plus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Rayleigh.pValues.Kolmogorov_D_Plus),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.LogNormal.pValues.Kolmogorov_D_Plus),'$} \\ \cline{3-11}'];
tobuild{031} = ['& & Kol D- & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Exponential.pValues.Kolmogorov_D_Minus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Gamma.pValues.Kolmogorov_D_Minus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Rayleigh.pValues.Kolmogorov_D_Minus),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.LogNormal.pValues.Kolmogorov_D_Minus),'$} \\ \cline{3-11}'];
tobuild{032} = ['& & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Exponential.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Gamma.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Rayleigh.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.LogNormal.pValues.Kolmogorov_D),'$} \\ \cline{3-11}'];
tobuild{033} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Exponential.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Gamma.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Rayleigh.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.LogNormal.pValues.Cramer_von_Mises),'$} \\ \cline{3-11}'];
tobuild{034} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Exponential.pValues.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Gamma.pValues.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Rayleigh.pValues.Kuiper),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.LogNormal.pValues.Kuiper),'$} \\ \cline{3-11}'];
tobuild{035} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Exponential.pValues.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Gamma.pValues.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Rayleigh.pValues.Watson),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.LogNormal.pValues.Watson),'$} \\ \cline{3-11}'];
tobuild{036} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Exponential.pValues.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Gamma.pValues.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.Rayleigh.pValues.Anderson_Darling),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActivityPotential_FitTool.LogNormal.pValues.Anderson_Darling),'$} \\ \hline'];
tobuild{037} = '\end{tabular}';
%Begin Interaction Times Results
tobuild{038} = '\newpage';
tobuild{039} = '\begin{tabular}{|c|c|c||c|c||c|c||c|c||c|c|} \hline';
tobuild{040} = '\multicolumn{3}{|c||}{\textbf{Int. Times}} & \multicolumn{2}{c||}{\textbf{Exponential}} & \multicolumn{2}{c||}{\textbf{Mittag-Lefflar}} & \multicolumn{2}{c||}{\textbf{Gen. Pareto}} & \multicolumn{2}{c|}{\textbf{Weibull}} \\ \hline';
tobuild{041} = ['\parbox[t]{2mm}{\multirow{17}{*}{\rotatebox[origin=c]{90}{Method of Moments}}} & \multicolumn{2}{|c||}{\multirow{3}{*}{\textbf{Parameters}}} & \multirow{3}{*}{Rate} & \multirow{3}{*}{$',num2matlabstr(Analysis.InteractionTimes_Moments.Exponential.Parameters.Scale),'$} & Stability & $X$ & Shape & $',num2matlabstr(Analysis.InteractionTimes_Moments.GenPareto.Parameters.Shape),'$ & Scale & $X$ \\ \cline{6-11}'];
tobuild{042} = ['& \multicolumn{2}{|c||}{} & & & \multirow{2}{*}{Scale} & \multirow{2}{*}{$X$} & Scale & $',num2matlabstr(Analysis.InteractionTimes_Moments.GenPareto.Parameters.Scale),'$ & \multirow{2}{*}{Shape} & \multirow{2}{*}{$X$} \\ \cline{8-9}'];
tobuild{043} = ['& \multicolumn{2}{|c||}{} & & & & & Loc. & $',num2matlabstr(Analysis.InteractionTimes_Moments.GenPareto.Parameters.Location),'$ & & \\ \cline{2-11}'];
tobuild{044} = ['& \parbox[t]{2mm}{\multirow{7}{*}{\rotatebox[origin=c]{90}{Statistics}}} & Kol D+ & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.Exponential.Statistics.Kolmogorov_D_Plus),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.GenPareto.Statistics.Kolmogorov_D_Plus),'$} & \multicolumn{2}{c|}{$X$} \\ \cline{3-11}'];
tobuild{045} = ['& & Kol D- & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.Exponential.Statistics.Kolmogorov_D_Minus),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.GenPareto.Statistics.Kolmogorov_D_Minus),'$} & \multicolumn{2}{c|}{$X$} \\ \cline{3-11}'];
tobuild{046} = ['& & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.Exponential.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.GenPareto.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c|}{$X$} \\ \cline{3-11}'];
tobuild{047} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.Exponential.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.GenPareto.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c|}{$X$} \\ \cline{3-11}'];
tobuild{048} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.Exponential.Statistics.Kuiper),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.GenPareto.Statistics.Kuiper),'$} & \multicolumn{2}{c|}{$X$} \\ \cline{3-11}'];
tobuild{049} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.Exponential.Statistics.Watson),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.GenPareto.Statistics.Watson),'$} & \multicolumn{2}{c|}{$X$} \\ \cline{3-11}'];
tobuild{050} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.Exponential.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.GenPareto.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c|}{$X$} \\ \cline{2-11}'];
tobuild{051} = ['& \parbox[t]{2mm}{\multirow{7}{*}{\rotatebox[origin=c]{90}{p-Values}}} & Kol D+ & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.Exponential.pValues.Kolmogorov_D_Plus),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.GenPareto.pValues.Kolmogorov_D_Plus),'$} & \multicolumn{2}{c|}{$X$} \\ \cline{3-11}'];
tobuild{052} = ['& & Kol D- & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.Exponential.pValues.Kolmogorov_D_Minus),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.GenPareto.pValues.Kolmogorov_D_Minus),'$} & \multicolumn{2}{c|}{$X$} \\ \cline{3-11}'];
tobuild{053} = ['& & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.Exponential.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.GenPareto.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c|}{$X$} \\ \cline{3-11}'];
tobuild{054} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.Exponential.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.GenPareto.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c|}{$X$} \\ \cline{3-11}'];
tobuild{055} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.Exponential.pValues.Kuiper),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.GenPareto.pValues.Kuiper),'$} & \multicolumn{2}{c|}{$X$} \\ \cline{3-11}'];
tobuild{056} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.Exponential.pValues.Watson),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.GenPareto.pValues.Watson),'$} & \multicolumn{2}{c|}{$X$} \\ \cline{3-11}'];
tobuild{057} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.Exponential.pValues.Anderson_Darling),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.InteractionTimes_Moments.GenPareto.pValues.Anderson_Darling),'$} & \multicolumn{2}{c|}{$X$} \\ \hline \hline'];
tobuild{058} = 
tobuild{059} = 
tobuild{060} = 
tobuild{061} = 
tobuild{062} = 
tobuild{063} = 
tobuild{064} = 
tobuild{065} = 
tobuild{066} = 
tobuild{067} = 
tobuild{068} = 
tobuild{069} = 
tobuild{070} = 
tobuild{071} = 
tobuild{072} = 
tobuild{073} = 
tobuild{074} = 
tobuild{075} = 
tobuild{076} = '\end{tabular}';
%Begin Active Links Results
tobuild{077} = '\newpage';
tobuild{078} = '\begin{tabular}{|c|c|c||c|c||c|c||c|c||c|c|} \hline';
tobuild{079} = '\multicolumn{3}{|c||}{Links Active} & \multicolumn{2}{c||}{\textbf{Exponential}} & \multicolumn{2}{c||}{\textbf{Gamma}} & \multicolumn{2}{c||}{\textbf{Rayleigh}} & \multicolumn{2}{c|}{\textbf{Log-Normal}} \\ \hline';
tobuild{080} = ['\parbox[t]{2mm}{\multirow{16}{*}{\rotatebox[origin=c]{90}{Method of Moments}}} & \multicolumn{2}{|c||}{\multirow{2}{*}{\textbf{Parameters}}} & \multirow{2}{*}{Rate} & \multirow{2}{*}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Exponential.Parameters.Scale),'$} & Shape & $',num2matlabstr(Analysis.ActiveLinks_Moments.Gamma.Parameters.Shape),'$ & \multirow{2}{*}{Scale} & \multirow{2}{*}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Rayleigh.Parameters.Scale),'$} & Loc. & $',num2matlabstr(Analysis.ActiveLinks_Moments.LogNormal.Parameters.Location),'$ \\ \cline{6-7}\cline{10-11}'];
tobuild{081} = ['& \multicolumn{2}{|c||}{} & & & Scale & $',num2matlabstr(Analysis.ActiveLinks_Moments.Gamma.Parameters.Scale),'$ & & & Scale & $',num2matlabstr(Analysis.ActiveLinks_Moments.LogNormal.Parameters.Scale),'$ \\ \cline{2-11}'];
tobuild{082} = ['& \parbox[t]{2mm}{\multirow{7}{*}{\rotatebox[origin=c]{90}{Statistics}}} & Kol D+ & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Exponential.Statistics.Kolmogorov_D_Plus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Gamma.Statistics.Kolmogorov_D_Plus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Rayleigh.Statistics.Kolmogorov_D_Plus),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_Moments.LogNormal.Statistics.Kolmogorov_D_Plus),'$} \\ \cline{3-11}'];
tobuild{083} = ['& & Kol D- & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Exponential.Statistics.Kolmogorov_D_Minus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Gamma.Statistics.Kolmogorov_D_Minus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Rayleigh.Statistics.Kolmogorov_D_Minus),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_Moments.LogNormal.Statistics.Kolmogorov_D_Minus),'$} \\ \cline{3-11}'];
tobuild{084} = ['& & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Exponential.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Gamma.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Rayleigh.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_Moments.LogNormal.Statistics.Kolmogorov_D),'$} \\ \cline{3-11}'];
tobuild{085} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Exponential.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Gamma.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Rayleigh.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_Moments.LogNormal.Statistics.Cramer_von_Mises),'$} \\ \cline{3-11}'];
tobuild{086} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Exponential.Statistics.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Gamma.Statistics.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Rayleigh.Statistics.Kuiper),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_Moments.LogNormal.Statistics.Kuiper),'$} \\ \cline{3-11}'];
tobuild{087} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Exponential.Statistics.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Gamma.Statistics.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Rayleigh.Statistics.Watson),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_Moments.LogNormal.Statistics.Watson),'$} \\ \cline{3-11}'];
tobuild{088} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Exponential.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Gamma.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Rayleigh.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_Moments.LogNormal.Statistics.Anderson_Darling),'$} \\ \cline{2-11}'];
tobuild{089} = ['& \parbox[t]{2mm}{\multirow{7}{*}{\rotatebox[origin=c]{90}{p-Values}}} & Kol D+ & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Exponential.pValues.Kolmogorov_D_Plus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Gamma.pValues.Kolmogorov_D_Plus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Rayleigh.pValues.Kolmogorov_D_Plus),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_Moments.LogNormal.pValues.Kolmogorov_D_Plus),'$} \\ \cline{3-11}'];
tobuild{090} = ['& & Kol D- & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Exponential.pValues.Kolmogorov_D_Minus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Gamma.pValues.Kolmogorov_D_Minus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Rayleigh.pValues.Kolmogorov_D_Minus),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_Moments.LogNormal.pValues.Kolmogorov_D_Minus),'$} \\ \cline{3-11}'];
tobuild{091} = ['& & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Exponential.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Gamma.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Rayleigh.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_Moments.LogNormal.pValues.Kolmogorov_D),'$} \\ \cline{3-11}'];
tobuild{092} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Exponential.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Gamma.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Rayleigh.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_Moments.LogNormal.pValues.Cramer_von_Mises),'$} \\ \cline{3-11}'];
tobuild{093} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Exponential.pValues.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Gamma.pValues.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Rayleigh.pValues.Kuiper),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_Moments.LogNormal.pValues.Kuiper),'$} \\ \cline{3-11}'];
tobuild{094} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Exponential.pValues.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Gamma.pValues.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Rayleigh.pValues.Watson),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_Moments.LogNormal.pValues.Watson),'$} \\ \cline{3-11}'];
tobuild{095} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Exponential.pValues.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Gamma.pValues.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_Moments.Rayleigh.pValues.Anderson_Darling),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_Moments.LogNormal.pValues.Anderson_Darling),'$} \\ \hline \hline'];
tobuild{096} = ['\parbox[t]{2mm}{\multirow{16}{*}{\rotatebox[origin=c]{90}{Curve Fitting Tool}}} & \multicolumn{2}{|c||}{\multirow{2}{*}{\textbf{Parameters}}} & \multirow{2}{*}{Rate} & \multirow{2}{*}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Exponential.Parameters.Scale),'$} & Shape & $',num2matlabstr(Analysis.ActiveLinks_FitTool.Gamma.Parameters.Shape),'$ & \multirow{2}{*}{Scale} & \multirow{2}{*}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Rayleigh.Parameters.Scale),'$} & Loc. & $',num2matlabstr(Analysis.ActiveLinks_FitTool.LogNormal.Parameters.Location),'$ \\ \cline{6-7}\cline{10-11}'];
tobuild{097} = ['& \multicolumn{2}{|c||}{} & & & Scale & $',num2matlabstr(Analysis.ActiveLinks_FitTool.Gamma.Parameters.Scale),'$ & & & Scale & $',num2matlabstr(Analysis.ActiveLinks_FitTool.LogNormal.Parameters.Scale),'$ \\ \cline{2-11}'];
tobuild{098} = ['& \parbox[t]{2mm}{\multirow{7}{*}{\rotatebox[origin=c]{90}{Statistics}}} & Kol D+ & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Exponential.Statistics.Kolmogorov_D_Plus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Gamma.Statistics.Kolmogorov_D_Plus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Rayleigh.Statistics.Kolmogorov_D_Plus),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.LogNormal.Statistics.Kolmogorov_D_Plus),'$} \\ \cline{3-11}'];
tobuild{099} = ['& & Kol D- & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Exponential.Statistics.Kolmogorov_D_Minus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Gamma.Statistics.Kolmogorov_D_Minus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Rayleigh.Statistics.Kolmogorov_D_Minus),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.LogNormal.Statistics.Kolmogorov_D_Minus),'$} \\ \cline{3-11}'];
tobuild{100} = ['& & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Exponential.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Gamma.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Rayleigh.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.LogNormal.Statistics.Kolmogorov_D),'$} \\ \cline{3-11}'];
tobuild{101} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Exponential.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Gamma.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Rayleigh.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.LogNormal.Statistics.Cramer_von_Mises),'$} \\ \cline{3-11}'];
tobuild{102} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Exponential.Statistics.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Gamma.Statistics.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Rayleigh.Statistics.Kuiper),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.LogNormal.Statistics.Kuiper),'$} \\ \cline{3-11}'];
tobuild{103} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Exponential.Statistics.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Gamma.Statistics.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Rayleigh.Statistics.Watson),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.LogNormal.Statistics.Watson),'$} \\ \cline{3-11}'];
tobuild{104} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Exponential.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Gamma.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Rayleigh.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.LogNormal.Statistics.Anderson_Darling),'$} \\ \cline{2-11}'];
tobuild{105} = ['& \parbox[t]{2mm}{\multirow{7}{*}{\rotatebox[origin=c]{90}{p-Values}}} & Kol D+ & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Exponential.pValues.Kolmogorov_D_Plus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Gamma.pValues.Kolmogorov_D_Plus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Rayleigh.pValues.Kolmogorov_D_Plus),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.LogNormal.pValues.Kolmogorov_D_Plus),'$} \\ \cline{3-11}'];
tobuild{106} = ['& & Kol D- & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Exponential.pValues.Kolmogorov_D_Minus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Gamma.pValues.Kolmogorov_D_Minus),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Rayleigh.pValues.Kolmogorov_D_Minus),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.LogNormal.pValues.Kolmogorov_D_Minus),'$} \\ \cline{3-11}'];
tobuild{107} = ['& & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Exponential.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Gamma.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Rayleigh.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.LogNormal.pValues.Kolmogorov_D),'$} \\ \cline{3-11}'];
tobuild{108} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Exponential.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Gamma.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Rayleigh.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.LogNormal.pValues.Cramer_von_Mises),'$} \\ \cline{3-11}'];
tobuild{109} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Exponential.pValues.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Gamma.pValues.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Rayleigh.pValues.Kuiper),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.LogNormal.pValues.Kuiper),'$} \\ \cline{3-11}'];
tobuild{110} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Exponential.pValues.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Gamma.pValues.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Rayleigh.pValues.Watson),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.LogNormal.pValues.Watson),'$} \\ \cline{3-11}'];
tobuild{111} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Exponential.pValues.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Gamma.pValues.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.Rayleigh.pValues.Anderson_Darling),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Analysis.ActiveLinks_FitTool.LogNormal.pValues.Anderson_Darling),'$} \\ \hline'];






\parbox[t]{2mm}{\multirow{17}{*}{\rotatebox[origin=c]{90}{Curve Fitting Tool}}} & \multicolumn{2}{|c||}{\multirow{3}{*}{\textbf{Parameters}}} & \multirow{3}{*}{Rate} & \multirow{3}{*}{$X$} & Stability & $X$ & Shape & $X$ & Scale & $X$ \\ \cline{6-11}
& \multicolumn{2}{|c||}{} & & & \multirow{2}{*}{Scale} & \multirow{2}{*}{$X$} & Scale & $X$ & \multirow{2}{*}{Shape} & \multirow{2}{*}{$X$} \\ \cline{8-9}
& \multicolumn{2}{|c||}{} & & & & & Loc. & $X$ & & \\ \cline{2-11}
& \parbox[t]{2mm}{\multirow{7}{*}{\rotatebox[origin=c]{90}{Statistics}}} & Kol D+ & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c|}{$X$} \\ \cline{3-11}
& & Kol D- & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c|}{$X$} \\ \cline{3-11}
& & Kol D & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c|}{$X$} \\ \cline{3-11}
& & CvM & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c|}{$X$} \\ \cline{3-11}
& & Kuiper & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c|}{$X$} \\ \cline{3-11}
& & Watson & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c|}{$X$} \\ \cline{3-11}
& & And-Dar & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c|}{$X$} \\ \cline{2-11}
& \parbox[t]{2mm}{\multirow{7}{*}{\rotatebox[origin=c]{90}{p-Values}}} & Kol D+ & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c|}{$X$} \\ \cline{3-11}
& & Kol D- & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c|}{$X$} \\ \cline{3-11}
& & Kol D & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c|}{$X$} \\ \cline{3-11}
& & CvM & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c|}{$X$} \\ \cline{3-11}
& & Kuiper & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c|}{$X$} \\ \cline{3-11}
& & Watson & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c|}{$X$} \\ \cline{3-11}
& & And-Dar & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c|}{$X$} \\ \hline



fileID = fopen(filepath,'w');
fprintf(fileID,'%s\n',tobuild{:});
fclose(fileID);

end

